In [2]:
import pandas as pd

df = pd.read_excel(r'C:\Users\LENOVO\Downloads\Flight_Information.xlsx')
print(df)

     FlightID FlightNumber    Airline  Destination     Status
0        1001       FL1102  Airline D      Houston    On Time
1        1002       FL1435  Airline B      Chicago    On Time
2        1003       FL1860  Airline A     New York  Cancelled
3        1004       FL1270  Airline C      Chicago    Delayed
4        1005       FL1106  Airline C     New York    Delayed
..        ...          ...        ...          ...        ...
195      1196       FL1863  Airline C     New York  Cancelled
196      1197       FL1742  Airline A     New York    Delayed
197      1198       FL1240  Airline D  Los Angeles  Cancelled
198      1199       FL1563  Airline D      Chicago    On Time
199      1200       FL1095  Airline B      Houston    On Time

[200 rows x 5 columns]

In [4]:
df.isnull().sum()

FlightID        0
FlightNumber    0
Airline         0
Destination     0
Status          0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FlightID      200 non-null    int64
 1   FlightNumber  200 non-null    object
 2   Airline       200 non-null    object
 3   Destination   200 non-null    object
 4   Status        200 non-null    object
dtypes: int64(1), object(4)
memory usage: 7.9+ KB

##  Is there a relationship between the Airline and Flight Status? ##

``` null hypothesis - There's no relation between flight status and airline```
``` alternative hypothesis - There is relation between flight status and airline```

In [10]:
from scipy.stats import chi2_contingency

table = pd.crosstab(df['Status'], df['Airline']) # pd.crosstab creates frquency table
print(table)

Airline    Airline A  Airline B  Airline C  Airline D
Status
Cancelled         18          9         15         18
Delayed           15         10         15         18
On Time           15         22         19         26

In [23]:
#now running chi square test

chi2, p_value, dof, expected = chi2_contingency(table)

print(f'Chi2 value is {chi2}, p value is {p_value}')

Chi2 value is 5.026692061852325, p value is 0.5403942477512074

Here p value is 0.54 which is above 0.05, thus it fails to reject null hypothesis. We can say there is no relation between between flight status and airline.

Note — When to Use chi2_contingency() and chisquare()

chi2_contingency() → Used to test if there is a relationship between two categorical variables.
Example: Is there a relationship between Airline and Flight Status?
→ Needs a 2D contingency table (rows × columns).

chisquare() → Used to check if observed data fits an expected distribution (goodness of fit test). It needs one categorical column.
Example: Do the observed flight delays match the expected distribution?
→ Needs observed vs expected frequencies (1D array).

In [12]:
df

     FlightID FlightNumber    Airline  Destination     Status
0        1001       FL1102  Airline D      Houston    On Time
1        1002       FL1435  Airline B      Chicago    On Time
2        1003       FL1860  Airline A     New York  Cancelled
3        1004       FL1270  Airline C      Chicago    Delayed
4        1005       FL1106  Airline C     New York    Delayed
..        ...          ...        ...          ...        ...
195      1196       FL1863  Airline C     New York  Cancelled
196      1197       FL1742  Airline A     New York    Delayed
197      1198       FL1240  Airline D  Los Angeles  Cancelled
198      1199       FL1563  Airline D      Chicago    On Time
199      1200       FL1095  Airline B      Houston    On Time

[200 rows x 5 columns]

## Check if all airlines have equal number of flights

``` null hypothesis - all flights have equal no. of flights```
```` alternative hypothesis - all flights does not have equal no. of flights

In [16]:
count_flight = df['Airline'].value_counts().sort_values()
print(count_flight)

Airline
Airline B    41
Airline A    48
Airline C    49
Airline D    62
Name: count, dtype: int64

In [17]:
total = sum(count_flight)
print(total)

200

In [18]:
len(count_flight)

4

In [24]:
expected = [total/ len(count_flight)]* len(count_flight)
print(expected)

[50.0, 50.0, 50.0, 50.0]

In [25]:
from scipy.stats import chisquare

#performing chisquare test

chi2, p_value = chisquare(count_flight, expected)

print(f'chi2 is {chi2} and p_value is {p_value}')

chi2 is 4.6 and p_value is 0.2035420816793649

Here p_value is 0.20 is above 0.05, it fails to reject null hypothesis. So more or less all flights have equal no. of flights

# Anova Test - It needs numerical columns

Lets run anova test on uber dataset. To check if droploaction affects customer ratings
null hypothesis = no diffrenece
alternative = diffrence is there

In [26]:
import pandas as pd

uber_df = pd.read_csv(r'C:\Users\LENOVO\Desktop\Python\Internshala\Py_Stats_Z_Test _VS_T_Test_Uber_Dataset\archive (1)\ncr_ride_bookings.csv')
print(uber_df)

              Date      Time    Booking ID   Booking Status   Customer ID  \
0       2024-03-23  12:29:38  "CNR5884300"  No Driver Found  "CID1982111"
1       2024-11-29  18:01:39  "CNR1326809"       Incomplete  "CID4604802"
2       2024-08-23  08:56:10  "CNR8494506"        Completed  "CID9202816"
3       2024-10-21  17:17:25  "CNR8906825"        Completed  "CID2610914"
4       2024-09-16  22:08:00  "CNR1950162"        Completed  "CID9933542"
...            ...       ...           ...              ...           ...
149995  2024-11-11  19:34:01  "CNR6500631"        Completed  "CID4337371"
149996  2024-11-24  15:55:09  "CNR2468611"        Completed  "CID2325623"
149997  2024-09-18  10:55:15  "CNR6358306"        Completed  "CID9925486"
149998  2024-10-05  07:53:34  "CNR3030099"        Completed  "CID9415487"
149999  2024-03-10  15:38:03  "CNR3447390"        Completed  "CID4108667"

         Vehicle Type         Pickup Location      Drop Location  Avg VTAT  \
0               eBike             Palam Vihar            Jhilmil       NaN
1            Go Sedan           Shastri Nagar  Gurgaon Sector 56       4.9
2                Auto                 Khandsa      Malviya Nagar      13.4
3       Premier Sedan     Central Secretariat           Inderlok      13.1
4                Bike        Ghitorni Village        Khan Market       5.3
...               ...                     ...                ...       ...
149995        Go Mini                 MG Road           Ghitorni      10.2
149996        Go Mini        Golf Course Road         Akshardham       5.1
149997       Go Sedan  Satguru Ram Singh Marg           Jor Bagh       2.7
149998           Auto               Ghaziabad         Saidulajab       6.9
149999  Premier Sedan         Ashok Park Main  Gurgaon Sector 29       3.5

        Avg CTAT  ...  Reason for cancelling by Customer  \
0            NaN  ...                                NaN
1           14.0  ...                                NaN
2           25.8  ...                                NaN
3           28.5  ...                                NaN
4           19.6  ...                                NaN
...          ...  ...                                ...
149995      44.4  ...                                NaN
149996      30.8  ...                                NaN
149997      23.4  ...                                NaN
149998      39.6  ...                                NaN
149999      33.7  ...                                NaN

       Cancelled Rides by Driver  Driver Cancellation Reason Incomplete Rides  \
0                            NaN                         NaN              NaN
1                            NaN                         NaN              1.0
2                            NaN                         NaN              NaN
3                            NaN                         NaN              NaN
4                            NaN                         NaN              NaN
...                          ...                         ...              ...
149995                       NaN                         NaN              NaN
149996                       NaN                         NaN              NaN
149997                       NaN                         NaN              NaN
149998                       NaN                         NaN              NaN
149999                       NaN                         NaN              NaN

        Incomplete Rides Reason Booking Value  Ride Distance  Driver Ratings  \
0                           NaN           NaN            NaN             NaN
1             Vehicle Breakdown         237.0           5.73             NaN
2                           NaN         627.0          13.58             4.9
3                           NaN         416.0          34.02             4.6
4                           NaN         737.0          48.21             4.1
...                         ...           ...            ...             ...
149995                      NaN         475.0          40.08             3.7
149996                      NaN        1093.0          21.31             4.8
149997                      NaN         852.0          15.93             3.9
149998                      NaN         333.0          45.54             4.1
149999                      NaN         806.0          21.19             4.6

        Customer Rating  Payment Method
0                   NaN             NaN
1                   NaN             UPI
2                   4.9      Debit Card
3                   5.0             UPI
4                   4.3             UPI
...                 ...             ...
149995              4.1     Uber Wallet
149996              5.0             UPI
149997              4.4            Cash
149998              3.7             UPI
149999              4.9     Credit Card

[150000 rows x 21 columns]

In [27]:
uber_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [30]:
subset = uber_df[['Drop Location', 'Customer Rating']]

In [31]:
subset['Customer Rating'].fillna(subset['Customer Rating'].mean(), inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4880\551544222.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  subset['Customer Rating'].fillna(subset['Customer Rating'].mean(), inplace=True)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4880\551544222.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['Customer Rating'].fillna(subset['Customer Rating'].mean(), inplace=True)

In [32]:
subset

            Drop Location  Customer Rating
0                 Jhilmil         4.404584
1       Gurgaon Sector 56         4.404584
2           Malviya Nagar         4.900000
3                Inderlok         5.000000
4             Khan Market         4.300000
...                   ...              ...
149995           Ghitorni         4.100000
149996         Akshardham         5.000000
149997           Jor Bagh         4.400000
149998         Saidulajab         3.700000
149999  Gurgaon Sector 29         4.900000

[150000 rows x 2 columns]

In [33]:
subset.isnull().any(axis=1)

0         False
1         False
2         False
3         False
4         False
          ...
149995    False
149996    False
149997    False
149998    False
149999    False
Length: 150000, dtype: bool

In [38]:
## creating groups

groups = [g['Customer Rating'] for _, g in subset.groupby('Drop Location')]
print(groups)

[11        4.404584
231       4.600000
331       3.800000
680       4.404584
682       4.404584
            ...
149293    4.500000
149329    4.200000
149567    4.200000
149723    4.300000
149810    4.700000
Name: Customer Rating, Length: 850, dtype: float64, 9         4.404584
696       4.500000
834       4.300000
883       5.000000
1061      4.300000
            ...
149068    4.900000
149387    4.404584
149519    4.404584
149705    5.000000
149868    4.404584
Name: Customer Rating, Length: 845, dtype: float64, 60        3.300000
143       4.700000
529       4.600000
688       4.404584
1048      3.800000
            ...
149334    3.000000
149620    4.404584
149676    4.400000
149856    4.404584
149996    5.000000
Name: Customer Rating, Length: 856, dtype: float64, 234       5.000000
518       4.900000
676       4.300000
1090      3.800000
1185      4.404584
            ...
148438    5.000000
148509    5.000000
148880    4.404584
149175    4.200000
149504    4.404584
Name: Customer Rating, Length: 836, dtype: float64, 18        4.404584
24        4.600000
989       4.404584
1006      4.404584
1470      3.900000
            ...
149416    4.404584
149716    4.404584
149770    4.404584
149911    4.404584
149975    4.500000
Name: Customer Rating, Length: 830, dtype: float64, 45        4.404584
46        4.404584
215       4.404584
867       4.404584
1060      4.300000
            ...
148886    4.404584
149321    4.900000
149430    3.900000
149785    4.404584
149986    5.000000
Name: Customer Rating, Length: 784, dtype: float64, 345       4.404584
679       4.300000
736       4.500000
779       3.900000
840       4.200000
            ...
149370    4.600000
149418    4.600000
149640    5.000000
149829    4.404584
149830    4.404584
Name: Customer Rating, Length: 875, dtype: float64, 185       3.900000
665       4.800000
851       4.400000
1012      5.000000
1211      4.500000
            ...
148842    4.700000
148947    4.404584
148990    4.404584
149372    5.000000
149528    4.100000
Name: Customer Rating, Length: 857, dtype: float64, 258       4.900000
644       4.900000
667       4.700000
901       4.900000
924       4.400000
            ...
149181    4.404584
149204    4.800000
149720    4.200000
149820    4.900000
149899    3.000000
Name: Customer Rating, Length: 861, dtype: float64, 362       4.404584
429       4.500000
532       4.404584
821       4.300000
1017      5.000000
            ...
149122    4.300000
149312    4.900000
149510    4.404584
149603    4.404584
149836    4.404584
Name: Customer Rating, Length: 851, dtype: float64, 96        4.800000
458       4.600000
632       4.900000
739       4.404584
893       4.404584
            ...
149399    4.200000
149584    4.600000
149745    5.000000
149796    5.000000
149954    4.404584
Name: Customer Rating, Length: 936, dtype: float64, 129       4.300000
175       4.900000
406       5.000000
863       4.404584
1283      4.404584
            ...
148715    4.400000
148948    3.900000
149091    4.404584
149407    3.200000
149992    4.404584
Name: Customer Rating, Length: 815, dtype: float64, 140       4.100000
150       3.700000
240       4.200000
618       4.500000
1049      4.404584
            ...
149583    4.404584
149635    4.404584
149903    4.100000
149950    4.200000
149983    5.000000
Name: Customer Rating, Length: 843, dtype: float64, 56        4.404584
588       4.500000
886       4.404584
1166      4.300000
1249      4.800000
            ...
149444    4.200000
149472    4.700000
149494    4.404584
149779    4.404584
149813    4.600000
Name: Customer Rating, Length: 824, dtype: float64, 99        4.404584
200       4.404584
527       4.404584
584       4.404584
719       4.400000
            ...
148622    4.404584
148692    4.404584
148876    4.600000
148958    4.700000
149931    4.600000
Name: Customer Rating, Length: 815, dtype: float64, 105       5.000000
247       4.200000
381       4.900000
464       4.404584
585       4.600000
            ...
149385    4.300000
149455    4.404584
149580    4.404584
149622    4.900000
149709    4.404584
Name: Customer Rating, Length: 875, dtype: float64, 25        4.200000
137       4.800000
936       4.404584
1053      4.300000
1405      4.600000
            ...
148660    4.600000
148957    4.500000
149218    4.404584
149258    4.404584
149636    4.300000
Name: Customer Rating, Length: 815, dtype: float64, 54        4.404584
212       5.000000
444       3.800000
515       3.800000
709       4.404584
            ...
149249    4.404584
149358    4.404584
149394    4.600000
149475    4.600000
149712    4.300000
Name: Customer Rating, Length: 917, dtype: float64, 184       4.404584
211       4.800000
549       4.800000
729       4.404584
1231      3.500000
            ...
149325    4.404584
149415    4.900000
149544    4.404584
149808    4.404584
149876    4.300000
Name: Customer Rating, Length: 853, dtype: float64, 139       4.404584
182       4.404584
485       3.000000
517       4.900000
909       4.500000
            ...
147264    3.900000
147306    4.300000
148220    5.000000
148361    3.500000
148795    4.404584
Name: Customer Rating, Length: 792, dtype: float64, 21        4.200000
28        4.404584
112       4.400000
319       4.200000
422       4.800000
            ...
149317    4.404584
149413    4.404584
149604    3.700000
149837    4.600000
149846    4.900000
Name: Customer Rating, Length: 871, dtype: float64, 50        4.404584
118       4.404584
126       3.700000
447       4.404584
649       4.404584
            ...
149435    4.404584
149599    4.700000
149725    4.400000
149912    4.404584
149972    4.300000
Name: Customer Rating, Length: 826, dtype: float64, 120       4.900000
313       3.100000
439       4.404584
482       4.404584
538       4.404584
            ...
148045    4.400000
148134    4.500000
148339    4.404584
149065    4.300000
149203    4.900000
Name: Customer Rating, Length: 804, dtype: float64, 107       4.100000
230       4.900000
238       4.404584
560       4.400000
666       4.300000
            ...
148765    4.900000
148813    4.800000
149063    4.600000
149684    4.404584
149695    3.300000
Name: Customer Rating, Length: 847, dtype: float64, 382       4.404584
408       4.600000
475       4.500000
862       4.600000
1449      4.404584
            ...
148734    4.404584
148748    4.404584
148946    4.800000
149360    4.404584
149543    4.100000
Name: Customer Rating, Length: 873, dtype: float64, 80        4.900000
299       4.200000
346       4.600000
497       4.300000
542       4.404584
            ...
149193    4.400000
149529    4.200000
149562    4.404584
149656    3.700000
149805    4.404584
Name: Customer Rating, Length: 876, dtype: float64, 40        4.404584
260       4.404584
302       4.404584
372       4.900000
641       4.400000
            ...
149149    4.000000
149374    4.400000
149739    4.600000
149768    4.700000
149917    3.000000
Name: Customer Rating, Length: 808, dtype: float64, 373       4.404584
414       4.500000
861       5.000000
992       4.404584
1669      4.404584
            ...
148531    4.404584
149491    4.404584
149742    5.000000
149842    4.300000
149853    4.404584
Name: Customer Rating, Length: 846, dtype: float64, 7         4.200000
166       4.600000
322       3.000000
393       4.404584
534       4.700000
            ...
149432    4.200000
149471    4.300000
149488    4.404584
149788    4.700000
149823    4.300000
Name: Customer Rating, Length: 912, dtype: float64, 97        4.404584
165       4.200000
318       4.700000
535       4.404584
812       4.404584
            ...
149247    4.500000
149295    4.700000
149465    4.100000
149878    5.000000
149973    4.404584
Name: Customer Rating, Length: 837, dtype: float64, 101       4.404584
294       4.600000
677       4.200000
1316      4.300000
1476      4.100000
            ...
147937    5.000000
147942    4.404584
148120    4.404584
148861    4.900000
149596    4.404584
Name: Customer Rating, Length: 876, dtype: float64, 171       4.700000
249       4.900000
385       4.404584
394       4.600000
421       4.404584
            ...
149392    4.100000
149447    4.404584
149484    4.404584
149923    4.300000
149962    4.200000
Name: Customer Rating, Length: 855, dtype: float64, 114       4.404584
173       4.300000
404       4.300000
810       4.200000
1384      4.404584
            ...
149629    4.404584
149693    4.500000
149761    4.404584
149956    4.404584
149976    4.600000
Name: Customer Rating, Length: 879, dtype: float64, 492       4.404584
750       4.700000
795       3.000000
1088      4.300000
1093      4.404584
            ...
148269    4.404584
148993    4.300000
149780    4.300000
149799    4.900000
149852    4.300000
Name: Customer Rating, Length: 867, dtype: float64, 10        4.900000
57        4.404584
565       4.100000
922       4.404584
1141      4.404584
            ...
149123    4.600000
149422    4.600000
149618    4.200000
149688    3.900000
149847    4.700000
Name: Customer Rating, Length: 856, dtype: float64, 159       4.404584
167       4.404584
566       4.800000
595       4.000000
658       4.900000
            ...
149320    5.000000
149456    4.404584
149479    4.300000
149561    4.300000
149689    5.000000
Name: Customer Rating, Length: 864, dtype: float64, 14        4.400000
17        4.404584
218       4.200000
312       4.404584
335       4.900000
            ...
149371    4.404584
149468    4.404584
149827    4.404584
149970    4.100000
149990    4.404584
Name: Customer Rating, Length: 861, dtype: float64, 239       4.700000
512       4.404584
631       4.600000
897       4.300000
987       4.404584
            ...
149216    4.900000
149400    4.100000
149642    5.000000
149775    4.300000
149933    3.900000
Name: Customer Rating, Length: 878, dtype: float64, 188       4.404584
279       4.800000
347       4.200000
490       4.404584
837       4.700000
            ...
149176    4.300000
149901    4.404584
149958    4.404584
149964    4.600000
149995    4.100000
Name: Customer Rating, Length: 877, dtype: float64, 13        4.700000
34        4.404584
227       4.404584
367       4.700000
551       4.900000
            ...
149579    3.000000
149612    4.200000
149658    4.600000
149915    4.404584
149951    4.900000
Name: Customer Rating, Length: 815, dtype: float64, 174       4.404584
226       3.800000
277       4.100000
360       3.300000
636       3.600000
            ...
149045    4.404584
149191    5.000000
149332    4.404584
149351    4.900000
149786    4.100000
Name: Customer Rating, Length: 808, dtype: float64, 456       4.300000
575       4.300000
638       4.404584
789       4.700000
950       4.300000
            ...
149617    4.600000
149752    4.404584
149825    4.700000
149871    4.100000
149885    4.404584
Name: Customer Rating, Length: 837, dtype: float64, 145       4.600000
154       4.900000
191       4.500000
416       4.200000
610       4.404584
            ...
149390    4.200000
149602    4.900000
149606    4.200000
149756    4.400000
149802    4.200000
Name: Customer Rating, Length: 845, dtype: float64, 102       3.800000
355       4.404584
441       4.404584
605       4.300000
609       4.800000
            ...
149542    4.404584
149811    3.200000
149840    4.404584
149841    4.500000
149994    4.900000
Name: Customer Rating, Length: 875, dtype: float64, 64        4.404584
203       4.200000
241       4.600000
263       4.300000
391       4.404584
            ...
149384    3.800000
149502    4.500000
149591    4.800000
149673    4.900000
149717    4.404584
Name: Customer Rating, Length: 824, dtype: float64, 349       4.600000
402       4.300000
966       4.900000
1296      4.404584
1712      4.600000
            ...
149095    4.404584
149177    4.404584
149211    4.600000
149593    4.500000
149812    4.900000
Name: Customer Rating, Length: 891, dtype: float64, 95        4.404584
232       4.900000
419       4.404584
974       4.300000
1201      4.900000
            ...
148109    5.000000
148513    3.800000
148731    4.600000
148801    3.300000
149999    4.900000
Name: Customer Rating, Length: 827, dtype: float64, 1         4.404584
213       5.000000
290       4.000000
436       4.300000
608       4.404584
            ...
149223    4.100000
149476    4.800000
149507    4.404584
149527    4.400000
149724    4.404584
Name: Customer Rating, Length: 894, dtype: float64, 88        4.404584
219       4.300000
375       5.000000
459       4.500000
469       4.404584
            ...
149381    4.400000
149644    4.404584
149667    4.404584
149730    4.404584
149850    4.200000
Name: Customer Rating, Length: 878, dtype: float64, 133       4.100000
248       4.900000
327       3.700000
713       4.200000
763       4.100000
            ...
149520    4.404584
149548    4.000000
149747    4.404584
149803    4.404584
149864    4.300000
Name: Customer Rating, Length: 892, dtype: float64, 51        4.500000
106       4.404584
305       4.404584
320       4.404584
1008      4.404584
            ...
149340    4.600000
149485    3.600000
149557    4.500000
149626    5.000000
149628    5.000000
Name: Customer Rating, Length: 828, dtype: float64, 187       4.404584
494       4.404584
558       4.900000
939       4.404584
1154      4.300000
            ...
149344    4.900000
149352    4.404584
149366    4.404584
149835    4.404584
149965    4.404584
Name: Customer Rating, Length: 831, dtype: float64, 403       4.404584
506       4.404584
569       3.900000
796       4.100000
803       4.300000
            ...
149173    4.800000
149250    4.700000
149496    4.200000
149666    4.404584
149821    4.300000
Name: Customer Rating, Length: 774, dtype: float64, 84        3.600000
561       4.400000
583       4.500000
797       4.200000
925       4.300000
            ...
149171    4.300000
149230    4.404584
149600    4.100000
149703    4.400000
149981    4.100000
Name: Customer Rating, Length: 801, dtype: float64, 62        4.404584
273       3.800000
374       4.404584
477       4.404584
491       4.404584
            ...
148651    4.404584
149199    4.404584
149535    4.500000
149784    4.900000
149904    4.404584
Name: Customer Rating, Length: 828, dtype: float64, 103       4.800000
190       4.900000
229       4.300000
281       4.900000
336       4.800000
            ...
149490    4.900000
149698    4.404584
149719    4.500000
149952    4.404584
149955    4.300000
Name: Customer Rating, Length: 847, dtype: float64, 462       4.700000
582       4.404584
637       4.404584
733       4.600000
768       3.600000
            ...
149493    4.404584
149517    4.404584
149661    4.600000
149809    4.100000
149948    4.300000
Name: Customer Rating, Length: 856, dtype: float64, 22        3.600000
181       4.700000
192       4.300000
650       5.000000
794       4.100000
            ...
149406    4.404584
149469    4.200000
149595    4.404584
149782    4.800000
149804    4.500000
Name: Customer Rating, Length: 838, dtype: float64, 308       4.404584
321       4.404584
748       4.404584
957       4.404584
1290      4.700000
            ...
149166    4.404584
149197    4.200000
149214    4.404584
149405    4.600000
149920    3.900000
Name: Customer Rating, Length: 850, dtype: float64, 65        4.404584
389       4.404584
579       4.600000
623       4.404584
661       4.200000
            ...
148778    4.200000
148915    4.404584
149395    3.100000
149402    4.600000
149672    3.800000
Name: Customer Rating, Length: 853, dtype: float64, 3         5.000000
276       4.404584
348       4.404584
430       4.404584
892       4.404584
            ...
149449    4.700000
149741    4.700000
149772    4.600000
149834    4.300000
149937    4.404584
Name: Customer Rating, Length: 835, dtype: float64, 71        4.404584
237       4.100000
624       4.500000
672       3.600000
835       4.404584
            ...
149343    5.000000
149383    4.500000
149458    4.900000
149555    4.404584
149735    4.404584
Name: Customer Rating, Length: 867, dtype: float64, 288       4.404584
470       4.400000
657       4.404584
864       4.404584
985       4.404584
            ...
149426    3.200000
149443    4.404584
149452    4.404584
149553    4.400000
149758    4.900000
Name: Customer Rating, Length: 841, dtype: float64, 78        4.404584
130       3.900000
710       4.800000
977       4.600000
1276      5.000000
            ...
149473    4.404584
149503    4.600000
149524    4.800000
149751    4.300000
149765    4.300000
Name: Customer Rating, Length: 849, dtype: float64, 138       4.404584
466       4.700000
474       4.100000
511       4.404584
634       4.900000
            ...
149411    4.404584
149480    4.404584
149691    4.900000
149754    4.404584
149966    4.400000
Name: Customer Rating, Length: 838, dtype: float64, 127       4.300000
329       4.404584
337       4.404584
493       3.000000
622       4.300000
            ...
149744    4.200000
149831    4.100000
149927    4.700000
149987    4.500000
149993    4.700000
Name: Customer Rating, Length: 872, dtype: float64, 38        4.400000
268       4.404584
287       4.900000
409       4.100000
473       4.404584
            ...
149000    4.404584
149168    3.800000
149194    4.400000
149587    4.800000
149926    4.404584
Name: Customer Rating, Length: 859, dtype: float64, 90        4.404584
246       4.404584
379       4.300000
405       4.400000
533       4.404584
            ...
149206    4.404584
149246    3.400000
149260    5.000000
149271    4.404584
149729    4.400000
Name: Customer Rating, Length: 836, dtype: float64, 0         4.404584
359       4.404584
1095      4.404584
1709      3.900000
1887      4.300000
            ...
149053    3.100000
149268    4.400000
149348    4.404584
149514    4.300000
149692    4.100000
Name: Customer Rating, Length: 855, dtype: float64, 164       4.900000
539       4.404584
548       4.404584
653       4.600000
753       4.404584
            ...
148743    3.500000
149003    4.700000
149112    4.404584
149262    4.200000
149997    4.400000
Name: Customer Rating, Length: 831, dtype: float64, 674       4.100000
1234      4.404584
1826      4.700000
1837      4.404584
2035      4.404584
            ...
149589    4.100000
149686    4.404584
149711    4.200000
149795    4.800000
149943    4.404584
Name: Customer Rating, Length: 831, dtype: float64, 244       4.900000
293       4.100000
309       3.900000
457       4.800000
552       4.500000
            ...
149776    4.404584
149815    4.300000
149866    4.200000
149916    4.300000
149961    4.100000
Name: Customer Rating, Length: 912, dtype: float64, 714       4.700000
1104      4.404584
1236      4.000000
1304      4.200000
1821      4.404584
            ...
148865    4.404584
149136    4.404584
149333    4.600000
149832    4.900000
149877    3.200000
Name: Customer Rating, Length: 859, dtype: float64, 41        4.600000
49        3.300000
135       4.300000
366       4.500000
387       4.600000
            ...
148342    4.200000
148456    4.200000
149128    4.404584
149254    4.700000
149588    4.300000
Name: Customer Rating, Length: 856, dtype: float64, 82        4.200000
300       4.300000
643       4.600000
887       3.300000
888       4.404584
            ...
149318    4.404584
149481    4.200000
149680    4.200000
149865    4.404584
149880    4.404584
Name: Customer Rating, Length: 830, dtype: float64, 161       4.600000
205       4.404584
664       4.700000
708       4.404584
1116      4.400000
            ...
149144    4.300000
149251    3.900000
149347    4.404584
149844    4.100000
149848    4.404584
Name: Customer Rating, Length: 850, dtype: float64, 314       4.404584
407       4.404584
572       4.300000
670       4.200000
703       4.404584
            ...
148992    4.404584
149219    4.300000
149794    4.400000
149968    4.500000
149971    4.200000
Name: Customer Rating, Length: 909, dtype: float64, 115       4.404584
257       4.800000
361       4.404584
816       4.404584
975       4.200000
            ...
148470    4.404584

In [39]:
# running anova test

from scipy.stats import f_oneway

f_stat, p_value = f_oneway(*groups)

print(f'f_stat is {f_stat} and p_value is {p_value}')

f_stat is 0.9907593048161998 and p_value is 0.5203556983699706

**Here the p_value is 0.52 ahive is above 0.05, it fails to reject null hypothesis. So we can say drop loaction doesnt affect customer's rating much.**

| Thing                      | Meaning                                                         |
| -------------------------- | --------------------------------------------------------------- |
| `groupby('Drop Location')` | Breaks the big DataFrame into smaller groups based on locations |
| `g['Customer Rating']`     | Selects only the rating column from each small group            |
| `[ ... for _, g in ... ]`  | Creates a list of ratings for all locations                     |
| `groups`                   | A list of all ratings grouped by location                       |
| Numbers like 11, 231, 331  | Original DataFrame row indexes                                  |
| Locations                  | Stored separately as group names (`keys()`)                     |